server:
  port: ${PORT} #Porta em que ira rodar o microservice. ${PORT} = váriavel de ambiente do heroku, que utiliza a porta disponível para subir a aplicação.

ead:
  serviceRegistry: #usuário e senha padrão de autenticação do service registry. Os outros microservices só irão conseguir se registrar nesse eureka server, caso enviem esse usuário e senha.
    username: ${EUREKA_USERNAME} #Váriavel do heroku do username
    password: ${EUREKA_PASSWORD} #Váriavel do heroku da senha

eureka: #configurações eureka server
  client:
    registerWithEureka: false #Define para esse microservice não se registrar no eureka como cliente
    fetch-registry: false #Não buscar registro eureka
    service-url:   #Configuração para não exibir alertas de erros nos logs
      defaultZone: ${EUREKA_URL}
    instance: #Configurações que é obrigatório colocarmos, quando trabalhamos com service-registry e heroku.
      hostname: ${APP_DOMAIN_NAME}
      non-secure-port: 80